export const PokemonTypes = {
    //normal: { name: 'normal', id: '1' },
    //fighting: { name: 'fighting', id: '2' },
    //flying: { name: 'flying', id: '3' },
    //poison: { name: 'poison', id: '4' },
    ground: { name: 'ground', id: '5' },
    rock: { name: 'rock', id: '6' },
    bug: { name: 'bug', id: '7' },
    //ghost: { name: 'ghost', id: '8' },
    //steel: { name: 'steel', id: '9' },
    fire: { name: 'fire', id: '10' },
    water: { name: 'water', id: '11' },
    grass: { name: 'grass', id: '12' },
    electric: { name: 'electric', id: '13' },
    psychic: { name: 'psychic', id: '14' },
    ice: { name: 'ice', id: '15' },
    dragon: { name: 'dragon', id: '16' },
    //dark: { name: 'dark', id: '17' },
    //fairy: { name: 'fairy', id: '18' },
    //unknown: { name: 'unknown', id: '10001' },
    //shadow: { name: 'shadow', id: '10002' },
}